insert into work_list(ID, TODO) VALUES (1, '집안일');
insert into work_list(ID, TODO) VALUES (2, '빨래');
insert into work_list(ID, TODO) VALUES (3, '청소');
insert into work_list(ID, TODO) VALUES (4, '방청소');
insert into work_list(ID, TODO) VALUES (5, '집안일');
insert into work_list(ID, TODO) VALUES (6, '빨래');
insert into work_list(ID, TODO) VALUES (7, '청소');
insert into work_list(ID, TODO) VALUES (8, '방청소');
insert into work_list(ID, TODO) VALUES (9, '집안일');
insert into work_list(ID, TODO) VALUES (10, '빨래');
insert into work_list(ID, TODO) VALUES (11, '청소');
insert into work_list(ID, TODO) VALUES (12, '방청소');
insert into work_list(ID, TODO) VALUES (13, '집안일');
insert into work_list(ID, TODO) VALUES (14, '빨래');
insert into work_list(ID, TODO) VALUES (15, '청소');
insert into work_list(ID, TODO) VALUES (16, '방청소');
insert into id_ref values(2, 1);
insert into id_ref values(3, 1);
insert into id_ref values(4, 1);
insert into id_ref values(4, 3);
