CREATE TABLE WORK_LIST (
  ID int primary  key,
  TODO varchar(500),
  CREATED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  COMPLETED_YN BOOLEAN default FALSE ,
  COMPLETED_DATE TIMESTAMP
);

CREATE TABLE ID_REF (
  ID INT,
  REF_ID INT
);
